name: CI RDP Tailscale

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install & Connect Tailscale
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      run: |
        choco install tailscale -y
        $env:Path += ";C:\Program Files\Tailscale"
        tailscale up --authkey $env:TAILSCALE_AUTHKEY

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Password Account
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Keep Alive (RDP Active)
      run: |
        $env:Path += ";C:\Program Files\Tailscale"
        Write-Host "Tailscale IP:"
        tailscale ip -4
        Write-Host "RDP Siap Digunakan. Username: runneradmin | Password: P@ssw0rd!"
        while ($true) { Start-Sleep -Seconds 3600 }
        
