name: RDP Windows High Performance

on:
  workflow_dispatch:
    inputs:
      tailscale_key:
        description: 'Tempelkan Auth Key Tailscale (tskey-auth-...)'
        required: true
        type: string

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: High Performance & RDP Setup
        shell: powershell
        run: |
          powercfg -setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
          Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects' -Name "VisualFXSetting" -Value 2
          
          New-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT' -Name 'Terminal Services' -Force -ErrorAction SilentlyContinue | Out-Null
          New-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "DWMFRAMEINTERVAL" -PropertyType DWord -Value 15 -Force | Out-Null
          
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue
          
          $admin = [ADSI]"WinNT://./runneradmin,user"
          $admin.SetPassword("PasswordRDP123!")

      - name: Install & Connect Tailscale
        shell: powershell
        run: |
          $key = "${{ github.event.inputs.tailscale_key }}".Trim()
          if (-not $key) { Write-Error "Auth Key wajib diisi!"; exit 1 }

          choco install tailscale -y --no-progress
          
          $env:Path += ";C:\Program Files\Tailscale"
          Start-Sleep -Seconds 5
          
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey="$key" --unattended --accept-routes

      - name: Keep Alive
        shell: powershell
        run: |
          Write-Host "=========================================="
          Write-Host " RDP SIAP DIPAKAI"
          Write-Host " Username : runneradmin"
          Write-Host " Password : PasswordRDP123!"
          Write-Host "=========================================="
          $i = 0
          while ($i -lt 360) {
            Start-Sleep -Seconds 60
            $i++
          }
